<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php
            // Title
            echo $this->headTitle((string) $this->placeholder('headtitle'))->setSeparator(' - ')->setAutoEscape(false)->toString();

            // Head meta
            echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

            // Styles
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');

            // Scripts
            echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery-1.8.0.min.js');
        ?>
    </head>

    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar pull-right" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?=$this->basePath()?>"><?=$this->placeholder('headtitle')?></a>
                    <div class="nav-collapse">
                        <?php echo $this->navigation('Navigation')
                                ->menu()
                                ->setPartial('widget/navbar-menu.phtml')
                                ->render(); ?>

                        <?php if($this->moduleEnabled('WfkLocale')): ?>
                            <ul class="nav pull-right">
                                <li class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?=$this->translate('Language', 'wfklocale')?><b class="caret"></b></a>
                                    <?=$this->wfkLocale()->render(array('ulClass' => 'dropdown-menu'))?>
                                </li>
                            </ul>
                        <?php endif; ?>
                        <?=$this->partial('widget/navbar-user.phtml')?>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <?php echo $this->content; ?>
            </div>
            <hr>
            <footer>
                <p></p>
            </footer>
        </div> <!-- /container -->

        <?php echo $this->inlineScript() ?>
    </body>
</html>